import { getSession, signIn, signUp, resendVerification, signInWithAccountId, registerAnonymous, signOut, connect, disconnect, resolveClientLocation, getBillingStatus } from './auth.js';

const $ = (id) => document.getElementById(id);
const authView=$('authView'),mainView=$('mainView'),authForm=$('authForm'),authSubmit=$('authSubmit'),authMethodToggle=$('authMethodToggle'),emailFields=$('emailFields'),accountIdFields=$('accountIdFields'),anonHint=$('anonHint'),emailInput=$('email'),passwordInput=$('password'),accountIdInput=$('accountId'),statusBanner=$('statusBanner'),toggleBtn=$('toggleBtn'),upgradeBtn=$('upgradeBtn'),toggleLabel=$('toggleLabel'),connectionState=$('connectionState'),connectionTitle=$('connectionTitle'),scene=$('scene'),signOutBtn=$('signOutBtn'),routePath=$('routePath'),deviceDot=$('deviceDot'),serverDot=$('serverDot'),settingsButton=$('settingsButton'),settingsPanel=$('settingsPanel'),plansMenuBtn=$('plansMenuBtn'),networkMapBtn=$('networkMapBtn'),networkMapView=$('networkMapView'),dashboardView=$('dashboardView'),networkMapBack=$('networkMapBack'),trafficLabel=$('trafficLabel'),ipLabel=$('ipLabel'),ispDetail=$('ispDetail'),siteDetail=$('siteDetail'),trackerDetail=$('trackerDetail'),activityCarousel=$('activityCarousel'),connectionBadge=$('connectionBadge'),protectedMeta=$('protectedMeta'),mapConnectionText=$('mapConnectionText'),mapConnectionBadge=$('mapConnectionBadge');
let mode='signin',method='email',busy=false,subscriptionActive=false;
const MAP_WIDTH=340,MAP_HEIGHT=170;
const PARAGUAY={latitude:-25.2864,longitude:-57.647};

function project({latitude,longitude}){const lat=Math.max(-85,Math.min(85,Number(latitude)));const lon=Math.max(-180,Math.min(180,Number(longitude)));return{x:((lon+180)/360)*MAP_WIDTH,y:((90-lat)/180)*MAP_HEIGHT}}
function placePoint(element,point){element.setAttribute('cx',point.x.toFixed(2));element.setAttribute('cy',point.y.toFixed(2))}
function renderRoute(location){const server=project(PARAGUAY);placePoint(serverDot,server);if(!location||!Number.isFinite(Number(location.latitude))||!Number.isFinite(Number(location.longitude))){deviceDot.hidden=true;routePath.removeAttribute('d');return}const device=project(location);deviceDot.hidden=false;placePoint(deviceDot,device);const bend=Math.max(10,Math.min(36,Math.abs(server.x-device.x)*.22));const midX=(device.x+server.x)/2;const midY=Math.max(8,(device.y+server.y)/2-bend);routePath.setAttribute('d','M'+device.x.toFixed(2)+' '+device.y.toFixed(2)+' Q'+midX.toFixed(2)+' '+midY.toFixed(2)+' '+server.x.toFixed(2)+' '+server.y.toFixed(2))}
async function updateClientLocation(force=false){const location=await resolveClientLocation(force);renderRoute(location);return location}
function setSettingsOpen(open){settingsPanel.hidden=!open;settingsButton.setAttribute('aria-expanded',String(open))}
settingsButton.addEventListener('click',(event)=>{event.stopPropagation();setSettingsOpen(settingsPanel.hidden)});

document.addEventListener('click',(event)=>{if(!settingsPanel.hidden&&!settingsPanel.contains(event.target)&&!settingsButton.contains(event.target))setSettingsOpen(false)});
document.addEventListener('keydown',(event)=>{if(event.key==='Escape')setSettingsOpen(false)});

function showBanner(message,isError=false){statusBanner.hidden=!message;statusBanner.textContent=message||'';statusBanner.classList.toggle('error',isError)}
function syncAuthFields(){const email=method==='email';emailFields.hidden=!email;accountIdFields.hidden=!(method==='accountId'&&mode==='signin');anonHint.hidden=!(method==='accountId'&&mode==='signup');emailInput.required=email;passwordInput.required=email;passwordInput.minLength=10;accountIdInput.required=method==='accountId'&&mode==='signin';authSubmit.textContent=email?(mode==='signin'?'Sign in':'Create account'):(mode==='signin'?'Sign in with Account ID':'Create anonymous account');authMethodToggle.textContent=email?(mode==='signin'?'Sign in with Account ID instead':'Skip email — create anonymous account'):(mode==='signin'?'Sign in with email instead':'Use email instead')}
function setMode(next){mode=next;method='email';document.querySelectorAll('.tab').forEach(t=>t.classList.toggle('is-active',t.dataset.mode===mode));showBanner('');syncAuthFields()}
document.querySelectorAll('.tab').forEach(t=>t.addEventListener('click',()=>setMode(t.dataset.mode)));
authMethodToggle.addEventListener('click',()=>{method=method==='email'?'accountId':'email';showBanner('');syncAuthFields()});

function renderState(state){const encrypted=state==='connected',connecting=state==='connecting',blocked=state==='blocked';scene.classList.toggle('is-connecting',connecting);scene.classList.toggle('is-connected',encrypted);networkMapView.classList.toggle('is-connecting',connecting);networkMapView.classList.toggle('is-connected',encrypted);toggleBtn.disabled=connecting;toggleBtn.classList.toggle('is-disconnect',encrypted||blocked);connectionBadge.className='blueprint-badge'+(connecting?' connecting':'')+(encrypted?' connected':'');connectionBadge.querySelector('span').textContent=blocked?'BROWSER TRAFFIC BLOCKED':encrypted?'CONNECTION SECURED':connecting?'ESTABLISHING SECURE CONNECTION':'VPN DISCONNECTED';connectionTitle.textContent=blocked?'Browser traffic is blocked':encrypted?'You’re protected':'Your online activity is visible';connectionState.textContent=blocked?'The proxy stopped responding. Disconnect or reconnect to restore browser traffic.':encrypted?'Your Chrome traffic is encrypted and routed through VeritasVPN.':connecting?'Authenticating your account and validating encrypted internet access.':'Hide your IP address and encrypt your connection.';trafficLabel.textContent=blocked?'BROWSER TRAFFIC BLOCKED':encrypted?'ENCRYPTED TRAFFIC':'UNENCRYPTED TRAFFIC';ipLabel.textContent=blocked?'PROXY FAILED':encrypted?'IP HIDDEN':'IP VISIBLE';ispDetail.textContent=encrypted?'Sees encrypted data':'Can observe traffic';siteDetail.textContent=encrypted?'Sees the VPN IP':'Sees your IP';trackerDetail.textContent=encrypted?'Traffic is obscured':'Build a profile';activityCarousel.innerHTML=(encrypted?['Your activity is private','Your IP address is hidden','Trackers cannot inspect traffic']:['Sites you visit','Searches and activity','Your IP address']).map((text,index)=>`<span style="animation-delay:${index*1.9}s">${text}</span>`).join('');toggleLabel.textContent=blocked?'Disconnect':encrypted?'Disconnect':connecting?'Connecting…':'Connect now';toggleBtn.querySelector('i').textContent=blocked||encrypted?'×':connecting?'':'→';protectedMeta.hidden=!encrypted;mapConnectionText.textContent=blocked?'Browser traffic blocked':encrypted?'Encrypted route active':connecting?'Establishing route…':'No secure route';mapConnectionBadge.textContent=blocked?'BLOCKED':encrypted?'SECURED':connecting?'CONNECTING':'OFFLINE';mapConnectionBadge.classList.toggle('on',encrypted)}
async function refresh(){let session=await getSession();let billing={is_premium:false};if(session.user){billing=await getBillingStatus().catch(()=>({is_premium:false}));session=await getSession()}authView.hidden=!!session.user;mainView.hidden=!session.user;settingsButton.hidden=!session.user;document.body.classList.toggle('is-authenticated',!!session.user);toggleBtn.hidden=true;upgradeBtn.hidden=true;if(!session.user){subscriptionActive=false;setSettingsOpen(false);renderState('disconnected');syncAuthFields();return}subscriptionActive=billing.is_premium===true;plansMenuBtn.textContent=subscriptionActive?'Premium':'Plans';renderState(session.blocked?'blocked':session.connected?'connected':'disconnected');toggleBtn.hidden=!session.connected&&!subscriptionActive;upgradeBtn.hidden=session.connected||subscriptionActive;if(session.blocked)showBanner('Chrome traffic is blocked because the VPN proxy failed. Disconnect or reconnect to restore browsing.',true);await updateClientLocation(!session.connected)}

authForm.addEventListener('submit',async e=>{e.preventDefault();showBanner('');authSubmit.disabled=true;try{if(method==='accountId'){if(mode==='signin')await signInWithAccountId(accountIdInput.value);else{const user=await registerAnonymous();showBanner('Save this Account ID now—it cannot be recovered: '+user.account_id)}}else if(mode==='signin')await signIn(emailInput.value.trim(),passwordInput.value);else{const result=await signUp(emailInput.value.trim(),passwordInput.value);if(result.verification_required){showBanner('Check your inbox and verify your email before signing in.');return}}await refresh()}catch(err){showBanner(err.message||'Authentication failed.',true)}finally{authSubmit.disabled=false}});
function openPlans(){chrome.tabs.create({url:'https://veritasvpn.cloud/account/#/subscription'})}
upgradeBtn.addEventListener('click',openPlans);plansMenuBtn.addEventListener('click',()=>{setSettingsOpen(false);openPlans()});
networkMapBtn.addEventListener('click',()=>{setSettingsOpen(false);dashboardView.hidden=true;networkMapView.hidden=false;updateClientLocation(true)});networkMapBack.addEventListener('click',()=>{networkMapView.hidden=true;dashboardView.hidden=false});
toggleBtn.addEventListener('click',async()=>{if(busy)return;busy=true;showBanner('');const session=await getSession();try{if(session.connected){await disconnect();renderState('disconnected');toggleBtn.hidden=!subscriptionActive;await updateClientLocation(true)}else{if(!subscriptionActive){toggleBtn.hidden=true;throw new Error('An active subscription is required. Open settings to manage your subscription.')}renderState('connecting');const result=await connect();renderRoute(result.clientLocation);renderState('connected');showBanner('')}}catch(err){renderState('disconnected');showBanner(err.message||'Connection failed. Chrome’s normal connection was restored.',true)}finally{busy=false}});
signOutBtn.addEventListener('click',async()=>{const session=await getSession();if(session.connected&&!confirm('Signing out will disconnect your VPN. Continue?'))return;setSettingsOpen(false);await signOut();showBanner('');await refresh()});
renderRoute(null);syncAuthFields();refresh().catch(err=>showBanner(err.message||'Could not load VeritasVPN.',true));
