apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: btcpay

resources:
  - namespace.yaml
  - secrets.yaml
  - postgres-btcpay.yaml
  - bitcoind.yaml
  - bitcoin-readiness.yaml
  - nbxplorer.yaml
  - btcpayserver.yaml
  - network-policies.yaml

images:
  - name: localhost:31500/bitcoin-readiness
    newName: localhost:31500/bitcoin-readiness
    digest: sha256:59644d04f9c4b7baf349165283a6001b2d45786fe4deef02895b14402bea2ab5
