apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: btcpay

resources:
  - namespace.yaml
  - secrets.yaml
  - postgres-btcpay.yaml
  - bitcoind.yaml
  - bitcoin-readiness.yaml
  - nbxplorer.yaml
  - btcpayserver.yaml
  - network-policies.yaml

images:
  - name: localhost:31500/bitcoin-readiness
    newName: localhost:31500/bitcoin-readiness
    digest: sha256:9a3d1965eec510856ab9a4e2e88b491a279192f207c40e5b6ee0abd27521e99e
