apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: btcpay

resources:
  - namespace.yaml
  - secrets.yaml
  - postgres-btcpay.yaml
  - bitcoind.yaml
  - bitcoin-readiness.yaml
  - nbxplorer.yaml
  - btcpayserver.yaml
  - network-policies.yaml

images:
  - name: localhost:31500/bitcoin-readiness
    newName: localhost:31500/bitcoin-readiness
    digest: sha256:6c48a002c727115c3b7aa9ed3870fff5367a87a3284858b61787c0b85451187a
