apiVersion: v1
kind: ConfigMap
metadata:
  name: alertmanager-config
  namespace: monitoring
data:
  alertmanager.yml: |
    global:
      resolve_timeout: 5m
    route:
      group_by: ["alertname", "severity", "namespace", "job"]
      group_wait: 30s
      group_interval: 10m
      repeat_interval: 6h
      receiver: telegram-critical-warning
      routes:
        - matchers: [severity=~"critical|warning"]
          receiver: telegram-critical-warning
        - matchers: [severity="info"]
          receiver: null-receiver
    receivers:
      - name: telegram-critical-warning
        telegram_configs:
          - bot_token: "${TELEGRAM_BOT_TOKEN}"
            chat_id: 8005409602
            parse_mode: HTML
            send_resolved: true
            message: |
              <b>{{ .Status | toUpper }} · {{ .CommonLabels.severity | toUpper }}</b>
              {{ range .Alerts }}
              <b>{{ .Labels.alertname }}</b>
              {{ .Annotations.summary }}
              {{ .Annotations.description }}
              {{ end }}
      - name: null-receiver
    inhibit_rules:
      - source_matchers: [severity="critical"]
        target_matchers: [severity="warning"]
        equal: ["alertname", "namespace", "job"]
