apiVersion: 1
datasources:
  - name: Prometheus
    uid: prometheus
    type: prometheus
    access: proxy
    url: http://prometheus.monitoring.svc.cluster.local:9090
    isDefault: true
    editable: false
    jsonData:
      timeInterval: 15s
  - name: VeritasDB
    uid: postgres
    type: postgres
    access: proxy
    url: postgres.veritas.svc.cluster.local:5432
    user: analytics_reader
    database: veritas
    editable: false
    secureJsonData:
      password: $ANALYTICS_DB_PASSWORD
    jsonData:
      database: veritas
      sslmode: disable
      postgresVersion: 1600
      timescaledb: false
