apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - prometheus.yaml
  - exporters.yaml
  - grafana.yaml
  - network-policies.yaml
  - network-policies-namespace.yaml
configMapGenerator:
  - name: prometheus-config
    namespace: monitoring
    files: [prometheus.yml]
  - name: prometheus-rules
    namespace: monitoring
    files: [alerts.yml]
  - name: blackbox-config
    namespace: monitoring
    files: [blackbox.yml]
  - name: grafana-datasources
    namespace: monitoring
    files:
      - datasources.yml=grafana-datasources.yml
  - name: grafana-providers
    namespace: monitoring
    files:
      - dashboards.yml=grafana-dashboards.yml
  - name: grafana-dashboard
    namespace: monitoring
    files:
      - veritasvpn-overview.json=dashboards/veritasvpn-overview.json
generatorOptions:
  disableNameSuffixHash: true
